version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: hukukrobotu_backend
    container_name: Hukukrobotu_Backend
    command: python3 manage.py runserver 0.0.0.0:8000