version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - "8000:8000"
      
    stdin_open: true
    tty: true
    

    image: hukukrobotu_backend
    
    

    container_name: Hukukrobotu_Backend
